### ISSUE TITLE
[1.10.2]Can't make Earth Drop using multiblock structure.

### ISSUE THREAD

**Issue by SOL3675** [TheLMiffy1111/EssentialCraft4Unofficial#14]
The other drops generated with multiblock, but earth drops does not.
Using the version 4.7.1102.14 of essentialcraft 4 unofficial.

![2017-05-26_18 00 25](https://cloud.githubusercontent.com/assets/16431933/26488289/dbcd7730-423d-11e7-9aee-0de1308cfce8.png)

**Comment by TheLMiffy1111** [comment]
I changed the structure for the earth drops from using moss stone to grass

**Comment by SOL3675** [comment]
Oh, I'm sorry. The correct structure written in the research book.
Thank you for your response.
