### ISSUE TITLE
Worldgen lag [1.12.2]

### ISSUE THREAD

**Issue by frank89722** [TheLMiffy1111/EssentialCraft4Unofficial#19]
`[Server thread/WARN] [FML]: Essential Craft 4 Unofficial loaded a new chunk (4, -1  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.`
`[Server thread/WARN] [FML]: Essential Craft 4 Unofficial loaded a new chunk (3, 0  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.`
`[Server thread/WARN] [FML]: Essential Craft 4 Unofficial loaded a new chunk (2, 0  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.`
`[Server thread/WARN] [FML]: Essential Craft 4 Unofficial loaded a new chunk (1, -1  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.`
`[Server thread/WARN] [FML]: Essential Craft 4 Unofficial loaded a new chunk (23, -2  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.`
`[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3025ms behind, skipping 60 tick(s)
`

Let me know if you need more information :)

**Comment by TheLMiffy1111** [comment]
i think i may have fixed this in dev
