### ISSUE TITLE
Server crash MC1.12.2

### ISSUE THREAD

**Issue by frank89722** [TheLMiffy1111/EssentialCraft4Unofficial#22]
This is my first time run this mod in server side and it crashed on startup

EssentialCraft version:4.8.112.2

[crash report](https://pastebin.com/6fXH8qiq)

**Comment by hextrace** [comment]
For what it's worth, this problem also occurs in MC 1.12.1. ( crash-report: https://paste.ee/p/qCd7z )

EssentialCraftUnofficial-4.8.112.2.jar 
forge-1.12.1-14.22.1.2485-universal.jar

**Comment by austin-wiechman** [comment]
I am having this issue aswell.
