### ISSUE TITLE
Magical Water Uncraftable [1.12.2]

### ISSUE THREAD

**Issue by Entayan** [TheLMiffy1111/EssentialCraft4Unofficial#26]
Trying to make magical water in the magician table but no potion seems to work. I may be missing something but the recipe looks like it's supposed to accept any potion.

**Comment by TheLMiffy1111** [comment]
have you tried a normal bottle of water

**Comment by Entayan** [comment]
I've tried a normal bottle of water and every permutation of potions that I could think of.

**Comment by Way-Duy** [comment]
I believe the recipe called for "uncraftable potion" in the inventory mod I was using and I also encountered the same problem. MRU readings in the blocks was off but i was able to create other things that took similar amounts of time and MRU.
