### ISSUE TITLE
Crafting more than one item

### ISSUE THREAD

**Issue by Way-Duy** [TheLMiffy1111/EssentialCraft4Unofficial#27]
Any crafting done by EssentialCraft blocks/structures using more than exactly one of each item in the slot does not get accepted, which can be worked around with most recipes, but for things like the mithriline furnace requiring 2 blaze rods for 3 ender pearls, it seems that the mod doesn't recognize the 2 blaze rods as an acceptable input. Also the same for wanting to craft multiple of an item, like magic fortified stone. I must put the stone and iron each one at a time.

**Comment by TheLMiffy1111** [comment]
I believe this problem is in DummyCore, will fix
