### ISSUE TITLE
Graphical/Aesthetic issues

### ISSUE THREAD

**Issue by Way-Duy** [TheLMiffy1111/EssentialCraft4Unofficial#28]
I don't mean to overload you and also these are probably last on the priority list but nonetheless I'll post them here for reference if nothing else.  Structures and Crafting blocks both don't show their effects when crafting like they used to, IE the purple bars in the magician table. I suspect the same problem for the mithriline furnace and other structures but was unable to test due to the crafting multiple items issue and uncraftable potion in survival.  As always MRU readings are questionable at best (How much MRU the block has versus how much the block UI believes it has. Also includes soulstones.) I didn't test the MRU multiblock structure, but if its anything like last time I played then it works way better than the other blocks at telling how much MRU it has.  Also my memory is not the best but if it was ever possible to read how much resource inside the mithriline furnace had it certainly isn't possible now.

**Comment by TheLMiffy1111** [comment]
sorry for the very late response here
can you see which ones are fixed now?
most of these are due to server/client desyncs

also the mithriline furnace does have a espe ui, it just doesn't have numbers

**Comment by Kataiser9** [comment]
(Edit: Ignore what this previously said, if you saw it. Was testing on the wrong version.)

Both of these issues seem to be fine for me now on the latest version (4.9.112.3).

**Comment by TheLMiffy1111** [comment]
I'll close this issue for now.
