### ISSUE TITLE
[1.12.2]Is Magic Fortified Plate craftable?

### ISSUE THREAD

**Issue by kevin60667** [TheLMiffy1111/EssentialCraft4Unofficial#31]
I can't craft a magic fortified plate by put a Magical Fortified Stone in the Magician Table.

EssentialCraft4Unofficial4.9.112.0

![mfp-1](https://user-images.githubusercontent.com/35786773/35366581-2ff9c4a8-01b5-11e8-8646-fda9aad65145.png)
![mfp-2](https://user-images.githubusercontent.com/35786773/35366591-34ec8df6-01b5-11e8-96ee-8c85e1bdffb1.png)
![mfp-3](https://user-images.githubusercontent.com/35786773/35366594-384bd47a-01b5-11e8-8675-0b20c70d43ff.png)

**Comment by TheLMiffy1111** [comment]
DummyCore issue, will fix
