### ISSUE TITLE
[1.12] Broken CraftTweaker Integration

### ISSUE THREAD

**Issue by MasterEnderman** [TheLMiffy1111/EssentialCraft4Unofficial#32]
Forge: 14.23.1.2606
DummyCore: 2.4.112.3
EssentialCraft4: 4.9.112.1

The CraftTweaker support for essentialcraft seems to be broken. i got the syntax from github
```
@ZenClass("mods.essentialcraft.MagicianTable")

public class MagicianTable {



    @ZenMethod

    public static void addRecipe(IIngredient[] ingredients, IItemStack output, int mru)
```
but after that it only says

`[INITIALIZATION][CLIENT][ERROR] 02_Recipes.zs:436 > No such member: essentialcraft`

This is my script:
```
mods.essentialcraft.MagicianTable.addRecipe([
<minecraft:tallgrass:2>,
<minecraft:tallgrass:2>,
<minecraft:red_mushroom>,
<minecraft:brown_mushroom>,
<minecraft:nether_wart>
],<roots:spirit_herb_item>,200);
```

**Comment by jaredlll08** [comment]
The issue is that the ZenClass' are being registered too late, they need to be done in preinit, or just use @ZenRegister to auto register for convenience.

**Comment by TheLMiffy1111** [comment]
forgot about @ZenRegister when porting, fixed in dev
