### ISSUE TITLE
Elemental Infused Ores texture mismatch and worlgen options[1.12]

### ISSUE THREAD

**Issue by dancc7t** [TheLMiffy1111/EssentialCraft4Unofficial#37]
Hello, first of all thanks for porting EssentialCraft4 to 1.12.2, i really enjoyed this mod back in 1.7.10, even though i got stuck after visiting Hoanna.

### Issue
I have tried the mod and i noticed the ores have mismatching textures starting from the last overworld elemental infused ore, which appears twice on jei, but when placed you see a nether ore texture.
Relating to the ores, i have not seen any worldgen option on the config, i am creating a modpack and i would like to include EssentialCraft4, Hoanna is a good place to make certain radioactive ores to spawn.
The thing is i cant disable oregen for all ElementalInfusedOres . Same goes with the mini dungeons with 4 chests 4 spawners and one mru entity on the middle (i dont know its id), they are everywhere just like in 1.7.10. I have posted a pic.

The easiest would be an option to disable orespawn and minidungeons , so i can use cofhworld to spawn them the way i see it fits in my modpack.

Thanks.

### Pics
https://imgur.com/a/JS76t

### Versions
-EssentialCraftUnofficial-4.9.112.3
-Forge Build 1.12.2-14.23.2.2625
-Minecraft 1.12.2

**Comment by TheLMiffy1111** [comment]
fixed model mismatch
