### ISSUE TITLE
Incredible axe damage speed [1.12 / 4.9.112.3]

### ISSUE THREAD

**Issue by MineWitherMC** [TheLMiffy1111/EssentialCraft4Unofficial#46]
Weakened elemental axe has damage speed of 11.
Elemental and Wind Infused Axes have damage speeds of 19.
It literally means you have super spam weapons with pretty high damage (6 for Elemental one, 7 for Wind one). All other axes in game have damage speeds of 0.5-1.1. If this is not intended, please fix it.

**Comment by MineWitherMC** [comment]
Also, Chaos Fork, Maces and Elemental Swords all have damage speeds of 0. That means player can attack with any speed with no penalty. This is a real issue. Please fix it.

**Comment by TheLMiffy1111** [comment]
fixed
