### ISSUE TITLE
Crash with magicBees

### ISSUE THREAD

**Issue by Ushupiuck** [TheLMiffy1111/EssentialCraft4Unofficial#5]
Put in Simple words. if you install MagicBees alongside EssentialCraft and EssentialThaumaturgy, Essentialcraft will crash. tested with Magic bees in and without it. This only happens when Magic bees is installed. (ClientSide crash to be precise)
To be precise, this crash happens when you're checking a certain page of the essentialcraft manual. it's on the gems section...
[crash-2017-03-15_23.35.17-client.txt](https://github.com/MagicBees/MagicBees/files/848941/crash-2017-03-15_23.35.17-client.txt)

There's the crashlog.
EDIT: I derped with version numbers since I'm a bit outdated, but still check! I'm now about to see if this also happens with latest of both Essential mods, which I suspect is the case.
Edit 2: confirmed with latest version too!

[crash-2017-03-17_00.14.24-client.txt](https://github.com/TheLMiffy1111/EssentialCraft4Unofficial/files/849566/crash-2017-03-17_00.14.24-client.txt)

**Comment by TheLMiffy1111** [comment]
Fixed

**Comment by Ushupiuck** [comment]
Thanks. I need to add, Further research made revealed that this crash came due to another mod, Thaumic Energistics... Apologies in advance for the delayed reply! (try a minimal pack with EssentialCraft, EssentialThaumaturgy, Thaumcraft, AE2 & TE. the ones in the pack to be precise).

What is odd. Is that MagicBees triggered the crash... lemme explain, I had another pack which had the same mods-- (including Thaumic Energistics) EssentialCraft included, and this problem did not present. until MB was installed. _**The odd part is that, while in that pack it got solved by removing MB, on the other, whose crash I'm giving you, it did not...**_ strange.

**Comment by TheLMiffy1111** [comment]
The two reasons that GuiResearchBook might crash are as following:
1. It's trying to draw an ItemStack with a damage value of OreDictionary.WILDCARD_VALUE
2. It's trying to draw a OreRecipe with a OreDictionary entry that doesn't have any ItemStacks registered with it.

The fix I made is a temporary one fixing the first one, will make a better fix.
