### ISSUE TITLE
Loading issue with gregtech

### ISSUE THREAD

**Issue by Lgk2** [TheLMiffy1111/EssentialCraft4Unofficial#58]
I get an error that looks like this: 

Description: Exception in server tick loop

com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Attempted to add a duplicate entry to pool: #gregtech:loot_1xitem.essentialcraft.genItem@40

https://pastebin.com/Fd18Rndk

**Comment by TheLMiffy1111** [comment]
GregTechCE/GregTech#247?

**Comment by Lgk2** [comment]
Yeah seems like that was the problem.
