### ISSUE TITLE
[Q] 1.10 port.

### ISSUE THREAD

**Issue by mrapplexz** [TheLMiffy1111/EssentialCraft4Unofficial#6]
Hello! I saw on CurseForge that the help wanted on the 1.10 port. How can I help you? I really like Modbder's mods.

**Comment by TheLMiffy1111** [comment]
Um, yes, sorry for not responding

**Comment by TheLMiffy1111** [comment]
Currently there are some rendering issues that i don't really know how to fix, and there might be a lot of bugs here and there

**Comment by TheLMiffy1111** [comment]
Also I need a build.gradle

**Comment by mrapplexz** [comment]
Oh, ok. I'm already created a Gradle script for local building.

**Comment by mrapplexz** [comment]
Also, how can I contact you? Have you a Discord/Twitter/other account?

**Comment by TheLMiffy1111** [comment]
Here's my discord server: https://discord.gg/S2GucNn
